language: node_js
cache:
  directories:
    - ~/.npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

stages:
  - test
  - name: release
    if: branch = master AND type IN (push)

jobs:
  include:
    # test stage: run Node in all maintained versions. Run unique checks only in the last
    - node_js: 4
    - node_js: 6
    - node_js: 8
    - node_js: 9
      script:
        - npm run test
        - npm run coverage:upload
        - npm run build:ts
        - npm run validate:dts
    # release stage: run semantic release & update the docs
    - stage: release
      node_js: lts/*
      script:
        - npm run build:flow
        - npm run build:ts
        - npm run semantic-release
    - node_js: lts/*
      script:
        - npm run build:docs
        - npm run deploy-docs
